package csv.hierarchy.pg.persistent.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Definition generated by hbm2java
 */
@Entity
@Table(name = "definition")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Definition implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Long id;
    @Column(name = "version", nullable = false)
    private Integer version;
    @Column(name = "hierarchy_id", nullable = false)
    private Long hierarchyId;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "effective_from", nullable = false, length = 29)
    private Timestamp effectiveFrom;
    @Column(name = "client_id", nullable = false)
    private Long clientId;
    @Column(name = "schema", nullable = false)
    private String schema;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_ts", nullable = false, length = 29)
    private Timestamp createTs;
}


