package csv.hierarchy.pg.persistent.entity;


import com.fasterxml.jackson.databind.JsonNode;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.Type;
import org.hibernate.type.SqlTypes;

/**
 * Node generated by hbm2java
 */
@Entity
@Table(name = "node")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Node {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "iid", unique = true, nullable = false)
    private Long iid;

    @Column(name = "definition_id", nullable = false)
    private Long definition;

    @Column(name = "id", nullable = false, length = 20)
    private String id;

    @Column(name = "level", length = 20)
    private String level;

    @Column(name = "depth", nullable = false)
    private Integer depth;

    @Column(name = "name", length = 20)
    private String name;

    @Column(name = "parent_id", nullable = false, length = 20)
    private String parentId;

    @Column(name = "leaf", nullable = false)
    private boolean leaf;

    @Column(name = "tree", nullable = false, columnDefinition = "ltree")
    @Type(LTreeType.class)
    private String tree;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "ext_data", columnDefinition = "jsonb")
    private JsonNode extData;
}


